version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run: pwd
workflows:
  version: 2
  build_and_test:
    - jobs:
        build:
          filters:
            branches:
              only:
                - feature/circle-on-demand        
