version: 2
jobs:
  testapp:
    ignore:
      - /.*/
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run: pwd
  lint:
    ignore:
      - /.*/
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run: pwd
workflows:
  version: 2
  build_and_test:
    jobs:
      - testapp
      - lint
