version: 2
jobs:
  build_and_deploy:
    branches:
      only:
        - /$./
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run: pwd
  build:
    branches:
      only:
        - /$./
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run: pwd