version: 2
jobs:
  build_and_deploy:
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run: pwd
  build:
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run: pwd
workflows:
  version: 2
    build_workflow:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - /$./